const engine = require('./premiere-engine.js');

const catalog = {
  presets: [
    {id:'drill-impact-01',name:'Drill Impact 01',cat:'Drill',type:'EFFECT STACK',stack:'ZOOM · SHAKE · FLASH · RGB'},
    {id:'oneclip-white-flash',name:'White Flash',cat:'Drill',type:'ONE CLIP',stack:'FLASH'},
    {id:'twoclip-whip',name:'Whip',cat:'Hype',type:'TWO CLIPS',stack:'WHIP · BLUR · RGB'},
    {id:'cinematic-zoom-cut',name:'Cinematic Zoom Cut',cat:'Cinematic',type:'TWO CLIPS',stack:'ZOOM · EASE · BLUR'}
  ]
};
const content=document.getElementById('content'),search=document.getElementById('search');
let selectedPreset=null;
function card(p){return `<div class="card" data-id="${p.id}"><b>${p.name}</b><span class="tag">${p.cat} · ${p.type}</span><div class="muted" style="margin-top:8px">${p.stack}</div></div>`}
function renderHome(){content.innerHTML=`<div class="hero"><h1>Turn raw footage into a music video.</h1><div class="muted">Effects, motion, transitions and sauce — built for drill, trap and cinematic edits.</div></div><div class="section">QUICK TOOLS</div><div class="grid">${['Shake','Flash','Glow','Velocity','Blur','RGB','Zoom','Grain'].map(x=>`<div class="card"><b>${x}</b><span class="tag">Quick effect</span></div>`).join('')}</div><div class="section">FEATURED</div><div class="grid">${catalog.presets.map(card).join('')}</div>`;bindCards()}
function renderPresets(filter=''){const list=catalog.presets.filter(p=>(p.name+' '+p.cat+' '+p.type).toLowerCase().includes(filter.toLowerCase()));content.innerHTML=`<div class="section">PRESET BROWSER</div><div class="grid">${list.map(card).join('')}</div>`;bindCards()}
function renderTransitions(){const one=['White Flash','Impact Zoom','Shake Hit','RGB Burst','Glitch Hit','Spin'];const two=['Whip','Zoom Cut','Push','Spin Cut','Flash Cut','RGB Cut','Blur Cut','Cinematic'];content.innerHTML=`<div class="section">ONE CLIP</div><div class="grid">${one.map(x=>`<div class="card transition-card" data-name="${x}" data-kind="ONE_CLIP"><b>${x}</b><span class="tag">Single clip</span></div>`).join('')}</div><div class="section">TWO CLIPS</div><div class="grid">${two.map(x=>`<div class="card transition-card" data-name="${x}" data-kind="TWO_CLIPS"><b>${x}</b><span class="tag">Two clips</span></div>`).join('')}</div>`;document.querySelectorAll('.transition-card').forEach(el=>el.onclick=()=>renderControls(el.dataset.name,el.dataset.kind))}
function renderControls(name,kind='EFFECT STACK'){selectedPreset=catalog.presets.find(p=>p.name===name)||{id:name.toLowerCase().replaceAll(' ','-'),name,type:kind,cat:'Custom',stack:name};content.innerHTML=`<div class="hero"><h1>${name}</h1><div class="muted">${kind} · editable control stack</div></div>${[['Amount',35],['Frequency',18],['Decay',55],['Blur',12]].map(([n,v])=>`<div class="control"><label>${n}</label><input data-control="${n.toLowerCase()}" type="range" min="0" max="100" value="${v}"></div>`).join('')}<div class="control"><label>Duration (frames)</label><input data-control="duration" type="number" value="3" min="1" max="30"></div><div id="status" class="muted" style="margin:12px 0"></div><div class="actions"><button id="reset">RESET</button><button id="save">SAVE PRESET</button><button id="apply" class="primary">APPLY</button></div>`;document.getElementById('reset').onclick=()=>renderControls(name,kind);document.getElementById('save').onclick=()=>setStatus('Preset saved locally for this session.');document.getElementById('apply').onclick=applyCurrent}
function readControls(){const out={};document.querySelectorAll('[data-control]').forEach(el=>out[el.dataset.control]=Number(el.value));return out}
async function applyCurrent(){setStatus('Checking Premiere selection…');try{const result=await engine.applyPreset(selectedPreset,readControls());setStatus(result.applied?`Applied to ${result.selectedClips} clip(s).`:`Connected to ${result.sequence}. ${result.reason}`)}catch(error){setStatus(`SRNC: ${error.message}`)}}
function setStatus(text){const el=document.getElementById('status');if(el)el.textContent=text}
function bindCards(){document.querySelectorAll('.card[data-id]').forEach(el=>el.onclick=()=>renderControls(el.querySelector('b').textContent,el.querySelector('.tag').textContent.split(' · ').pop()))}
document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=b.dataset.tab;if(t==='dashboard')renderHome();else if(t==='presets')renderPresets();else if(t==='transitions')renderTransitions();else renderPresets(t)});search.oninput=()=>renderPresets(search.value);renderHome();
