const catalog={presets:[{id:'drill-impact-01',name:'Drill Impact 01',cat:'Drill',type:'EFFECT STACK',stack:'ZOOM · SHAKE · FLASH · RGB'},{id:'oneclip-white-flash',name:'White Flash',cat:'Drill',type:'ONE CLIP',stack:'FLASH'},{id:'twoclip-whip',name:'Whip',cat:'Hype',type:'TWO CLIPS',stack:'WHIP · BLUR · RGB'},{id:'cinematic-zoom-cut',name:'Cinematic Zoom Cut',cat:'Cinematic',type:'TWO CLIPS',stack:'ZOOM · EASE · BLUR'}]};
const content=document.getElementById('content'),search=document.getElementById('search');
function card(p){return `<div class="card" data-id="${p.id}"><b>${p.name}</b><span class="tag">${p.cat} · ${p.type}</span><div class="muted" style="margin-top:8px">${p.stack}</div></div>`}
function renderHome(){content.innerHTML=`<div class="hero"><h1>Turn raw footage into a music video.</h1><div class="muted">Effects, motion, transitions and sauce — built for drill, trap and cinematic edits.</div></div><div class="section">QUICK TOOLS</div><div class="grid">${['Shake','Flash','Glow','Velocity','Blur','RGB','Zoom','Grain'].map(x=>`<div class="card"><b>${x}</b><span class="tag">Quick effect</span></div>`).join('')}</div><div class="section">FEATURED</div><div class="grid">${catalog.presets.map(card).join('')}</div>`;bindCards()}
function renderPresets(filter=''){const list=catalog.presets.filter(p=>(p.name+' '+p.cat+' '+p.type).toLowerCase().includes(filter.toLowerCase()));content.innerHTML=`<div class="section">PRESET BROWSER</div><div class="grid">${list.map(card).join('')}</div>`;bindCards()}
function renderTransitions(){content.innerHTML=`<div class="section">ONE CLIP</div><div class="grid">${['White Flash','Impact Zoom','Shake Hit','RGB Burst','Glitch Hit','Spin'].map(x=>`<div class="card"><b>${x}</b><span class="tag">Single clip</span></div>`).join('')}</div><div class="section">TWO CLIPS</div><div class="grid">${['Whip','Zoom Cut','Push','Spin Cut','Flash Cut','RGB Cut','Blur Cut','Cinematic'].map(x=>`<div class="card"><b>${x}</b><span class="tag">Two clips</span></div>`).join('')}</div>`}
function renderControls(name){content.innerHTML=`<div class="hero"><h1>${name}</h1><div class="muted">Editable preset stack</div></div>${[['Amount',35],['Frequency',18],['Decay',55],['Blur',12]].map(([n,v])=>`<div class="control"><label>${n}</label><input type="range" min="0" max="100" value="${v}"></div>`).join('')}<div class="control"><label>Duration (frames)</label><input type="number" value="3" min="1" max="30"></div><div class="actions"><button>RESET</button><button>SAVE PRESET</button><button class="primary">APPLY</button></div>`}
function bindCards(){document.querySelectorAll('.card[data-id]').forEach(el=>el.onclick=()=>renderControls(el.querySelector('b').textContent))}
document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=b.dataset.tab;if(t==='dashboard')renderHome();else if(t==='presets')renderPresets();else if(t==='transitions')renderTransitions();else renderPresets(t)});search.oninput=()=>renderPresets(search.value);renderHome();
